name = "TodoFiles"
uuid = "358ed29a-d93c-4fe8-8ea3-c6948dc61de3"
version = "0.1.0"
authors = ["Josh Day <emailjoshday@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Dates = "1.11.0"
Tables = "1.12.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
